apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ota-kube
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ota-kube
    spec:
      containers:
        - name: ota-kube
          image: bclouser/ota-kube
          ports:
            - name: http-port
              containerPort: 8080
          command: ["ota-kube"]
          tty: true
          stdin: true
      dnsPolicy: "ClusterFirst"