apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ota-kube
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ota-kube
    spec:
      containers:
        - name: ota-kube
          image: bclouser/ota-kube
          command: ["/usr/local/bin/ota-kube"]
          ports:
            - name: http-port
              containerPort: 8000
          tty: true
          stdin: true
          env: 
            - name: CREDENTIALS_DIR
              value: /data
            - name: DNS_NAME
              value: toradex.int
            - name: SERVER_NAME
              value: ota-ce.toradex.int
            - name: AUTOPROV_SERVER_NAME
              value: autoprov.dev2.inno

      dnsPolicy: "ClusterFirst"
---
apiVersion: v1
kind: Service
metadata:
  name: ota-kube-svc
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer
  selector:
    app: ota-kube
---
